###############################################################################
# Copyright CODESYS Development GmbH
###############################################################################

FROM osadl/debian-docker-base-image:bullseye-amd64-220419

USER root
ENV USER=root

EXPOSE 443   
EXPOSE 4840
EXPOSE 8080  
EXPOSE 11740

RUN apt-get update && apt-get install -y \
    libusb-1.0-0 \
    procps \
    libcap2-bin \
    && apt-get source --download-only \
    libcap2=1:2.44-1 \
    libcap2-bin=1:2.44-1 \
    libgpm2=1.20.7-8 \
    libncurses6=6.2+20201114-2 \
    libncursesw6=6.2+20201114-2 \
    libpam-cap=1:2.44-1 \
    libprocps8=2:3.3.17-5 \
    libusb-1.0-0=2:1.0.24-3 \
    procps=2:3.3.17-5 \
    psmisc=23.4-2 2>/dev/null \
    && rm -rf /var/lib/apt/lists/*

ARG CODEMETER_DEB=codemeter-lite_*_amd64.deb
ARG CODESYSCONTROL_DEB=codesyscontrol_linux_4.7.0.0*_amd64.deb
ADD ${CODEMETER_DEB} ${CODESYSCONTROL_DEB}  /tmp/ 
ADD Docker_copyright_* /

#RUN mkdir /work
#WORKDIR /work
#COPY codesysedge_edgeamd64_4.7.0.0-b.trunk.39_amd64.deb /work
#RUN dpkg -i --force-architecture codesysedge_edgeamd64_4.7.0.0-b.trunk.39_amd64.deb
#RUN rm codesysedge_edgeamd64_4.7.0.0-b.trunk.39_amd64.deb

RUN cd /tmp; dpkg -i ${CODEMETER_DEB}; rm ${CODEMETER_DEB}; cd /tmp; dpkg -i ${CODESYSCONTROL_DEB}; rm ${CODESYSCONTROL_DEB};

WORKDIR /var/opt/codesys/
ENTRYPOINT [ "/opt/codesys/scripts/startup.sh" ]
CMD []
